### ISSUE TITLE
[ERROR] solutions/LC/29-divide-two-integers.rs: compilation failed

### ISSUE THREAD

**Issue by mantou132** [bhuztez/porus#3]
OS: macOS
rustc: 1.30.0-nightly (67390c0c3 2018-08-14)

```
error[E0461]: couldn't find crate `porus` with expected target triple x86_64-apple-darwin
 --> solutions/LC/29-divide-two-integers.rs:5:1
  |
5 | extern crate porus;
  | ^^^^^^^^^^^^^^^^^^^
  |
  = note: the following crate versions were found:
          crate `porus`, target triple x86_64-unknown-linux-gnu: /Users/xxx/porus/target/x86_64-unknown-linux-gnu/release/libporus.rlib

error: aborting due to previous error
```

**Comment by mantou132** [comment]
https://github.com/japaric/rust-cross#cross-compiling-with-rustc

porus/ixcfg.py 101 line add: `"--target", llvm_target,`

**Comment by bhuztez** [comment]
Thanks for reporting. `--target llvm_target` has been missing since commit https://github.com/bhuztez/porus/commit/48a635ab3b4b723eed0b0c65beeb5b31450ae5a4 . As only `x86_64-unknown-linux-gnu` is required for both AOJ and Leetcode, this has not caused any trouble for quite a long time. Moreover, running solution locally on Mac OS X were not supported.

Now, it should just work. I have enabled testing on osx on travis-ci. Reopen this issue, If you still have trouble.
